name: Send Lichess Message

on:
  workflow_dispatch:
    inputs:
      player_name:
        description: "Lichess username to message"
        required: true
        type: string

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Send Lichess Message
        env:
          BR: "${{ secrets.L }}"
        run: python -u s.py "${{ github.event.inputs.player_name }}"
