name: Send Lichess team message

on:
  schedule:
    # 7:07 PM IST = 13:37 UTC on June 26
    - cron: '37 13 26 6 *'
  workflow_dispatch: {}  # Optional manual trigger

env:
  TEAM_ID: testingsboy
  MESSAGE: "⚠️ Reminder: Tournament starts at 7:30 PM IST! Join: https://lichess.org/tournament/ABC123"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send team message via Lichess API
        env:
          TOKEN: ${{ secrets.LICHESS_KEY }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            --data-urlencode "msg=$MESSAGE" \
            https://lichess.org/api/team/$TEAM_ID/pm-all
