name: Send Lichess Team Message

on:
  schedule:
    - cron: '14 14 * * *'  # 13:47 UTC = 7:17 PM IST
  workflow_dispatch: {}
  
jobs:
  message:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Send message
        env:
          LICHESS_KEY: ${{ secrets.LICHESS_KEY }}
        run: python send_team_msg.py
